adding github env

diff --git a/.github/workflows/lighthouse-ci.yaml b/.github/workflows/lighthouse-ci.yaml
--- a/.github/workflows/lighthouse-ci.yaml
+++ b/.github/workflows/lighthouse-ci.yaml
@@ -17,6 +17,6 @@ jobs:
         run: |
           npm install -g @lhci/cli@0.6.x
         run: npm run build
-      - run: lhci autorun--upload.target=temporary-public-storage || echo "LHCI failed!"
+        run: lhci autorun--upload.target=temporary-public-storage || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
